test.delta.sbrf.ru-nginx:
  connect: user@test.delta.sbrf.ru
  credID: nginxSshPrivKey
  typeDeploy: nginx
  configuration: https://github.com/latypovavictoria/masters_degree.git

test.delta.sbrf.ru-elk:
  connect: user@test.delta.sbrf.ru
  credID: elkSshPrivKey
  typeDeploy: elk
  configuration: https://github.com/latypovavictoria/masters_degree.git