version: '3'

services:
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-linux-agent
    restart: always
    environment:
      - JENKINS_URL=http://localhost:8080/
      - JENKINS_AGENT_NAME=linux-docker-agent
      - JENKINS_SECRET=a21cd764fd6a1f1d1cf05cba718af496ccb96e0bb8e7fb178fa0929a71bec682
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
