pipeline {
    agent { label 'linux-docker-agent' }

    environment {
        JENKINS_URL = 'http://localhost:8080'
        JENKINS_USER = 'admin'
        JENKINS_TOKEN = credentials('token_admin')
    }


    parameters {
        string(name: 'API_KEY', defaultValue: '', description: 'API KEY for NVD')
        string(name: 'CHECK_JENKINSFILE_PATH', defaultValue: 'Jenkinsfile', description: 'Path to Jenkinsfile for analysis')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/latypovavictoria/masters_degree.git', branch: 'main'
            }
        }

        stage('Install Requirements') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                        python3 -m pip install --upgrade pip
                        pip3 install requests junit-xml
                    '''
                    } else {
                        bat '''
                          python -m pip install --upgrade pip
                          pip install requests junit-xml
                    '''
                    }
                }
            }
        }

        stage('Run Plugin CVE Check') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                        python3 scripts_reports/plugin_check.py "$JENKINS_URL" "$JENKINS_USER" "$JENKINS_TOKEN" "${API_KEY}"
                    '''
                    } else {
                        bat '''
                          python scripts_reports/plugin_check.py "%JENKINS_URL%" "%JENKINS_USER%" "%JENKINS_TOKEN%" "%API_KEY%"
                    '''
                    }
                }
            }
        }

        stage('Analyze Jenkinsfile') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                        python3 scripts_reports/analyze_jenkinsfile.py "${CHECK_JENKINSFILE_PATH}"
                    '''
                    } else {
                        bat '''
                          python scripts_reports/analyze_jenkinsfile.py "%CHECK_JENKINSFILE_PATH%"
                    '''
                    }
                }
            }
        }

        stage('Generate JUnit Report') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                        python3 scripts_reports/generate_junit.py
                    '''
                    } else {
                        bat '''
                          python scripts_reports/generate_junit.py
                    '''
                    }
                }
            }
        }

        stage('Publish Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: '']]
                junit 'scripts_reports/security_result.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'scripts_reports/*.json', fingerprint: true
        }
    }
}
