pipeline {
    agent { label 'linux-docker-agent' }

    environment {
        JENKINS_URL = 'http://localhost:8080'
        JENKINS_USER = 'admin'
        JENKINS_TOKEN = credentials('token_admin')
    }

    parameters {
        string(name: 'API_KEY', defaultValue: '', description: 'API KEY for NVD')
        string(name: 'CHECK_JENKINSFILE_PATH', defaultValue: 'Jenkinsfile', description: 'Path to Jenkinsfile for analysis')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/latypovavictoria/masters_degree.git', branch: 'main'
            }
        }

        stage('Install Requirements') {
            steps {
                sh '''
                    python3 -m pip install --upgrade pip
                    pip3 install requests junit-xml
                '''
            }
        }

        stage('Run Plugin CVE Check') {
            steps {
                sh '''
                    python3 plugin_check.py "$JENKINS_URL" "$JENKINS_USER" "$JENKINS_TOKEN" "${API_KEY}"
                '''
            }
        }

        stage('Analyze Jenkinsfile') {
            steps {
                sh '''
                    python3 analyze_jenkinsfile.py "${CHECK_JENKINSFILE_PATH}"
                '''
            }
        }

        stage('Generate JUnit Report') {
            steps {
                sh '''
                    python3 generate_junit.py
                '''
            }
        }

        stage('Publish Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: '']]
                junit 'security_result.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '*.json', fingerprint: true
        }
    }
}
